-- 1. CAFE_TEMP 생성
use main_project;

-- DROP TABLE CAFE;
 DROP TABLE CAFE;
 DROP TABLE CAFE_TEMP;

CREATE TABLE CAFE_TEMP (
	CAFE_ID INT NOT NULL AUTO_INCREMENT,
	CAFE_NAME VARCHAR(100),
	SITE VARCHAR(300),
	CAFE_TYPE CHAR(1),
	ADD_ROAD VARCHAR(100),
	ADD_OLD	VARCHAR(100),
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE,
	OPEN_CLOSE VARCHAR(30),
	CAFE_TEL VARCHAR(15),
	SUB_INFO VARCHAR(100),
	WIFI CHAR(1),
	ANIENTRY CHAR(1),
	PARKING	CHAR(1),
	WHEELCHAIR CHAR(1),
	PLAYROOM CHAR(1),
	SMOKINGROOM	CHAR(1),
	TOTAL_POINTT INT,
	POINT1 FLOAT,
	POINT2 FLOAT,
	POINT3 FLOAT,
	POINT4 FLOAT,
	POINT5 FLOAT,
    MOOD CHAR(3),
	IMAGE_URL  VARCHAR	(1000),
	PRIMARY KEY (`CAFE_ID`)
);

-- 2. CAFE_TEMP 생성 후  *.CSV 파일 import 

/*----------------------------------*/
select count(*) from  CAFE_TEMP;
select * from CAFE_TEMP;

/*----------------------------------*/

-- 3. CAFE 생성
CREATE TABLE CAFE (
	CAFE_ID INT NOT NULL AUTO_INCREMENT,
	CAFE_NAME VARCHAR(100),
	SITE VARCHAR(300),
	CAFE_TYPE CHAR(1),
	ADD_ROAD VARCHAR(100),
	ADD_OLD	VARCHAR(100),
	LATITUDE DOUBLE,
	LONGITUDE DOUBLE,
	OPEN_CLOSE VARCHAR(30),
	CAFE_TEL VARCHAR(15),
	SUB_INFO VARCHAR(100),
	WIFI CHAR(1),
	ANIENTRY CHAR(1),
	PARKING	CHAR(1),
	WHEELCHAIR CHAR(1),
	PLAYROOM CHAR(1),
	SMOKINGROOM	CHAR(1),
	TOTAL_POINTT INT,
	POINT1 FLOAT,
	POINT2 FLOAT,
	POINT3 FLOAT,
	POINT4 FLOAT,
	POINT5 FLOAT,
    MOOD CHAR(3),
	IMAGE_URL  VARCHAR	(1000),
    REG_DATE DATETIME NOT NULL,
	MOD_DATE DATETIME,
	PRIMARY KEY (`CAFE_ID`)
);

/*----------------------------------*/
-- 4. REG_DATE, MOD_DATE 컬럼 포함한 CAFE 생성
insert into CAFE
select a.*, now(), null from CAFE_TEMP a;

/*----------------------------------*/

select count(*) from CAFE;
select * from CAFE;


